language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
- npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
- ./ci/doc.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "dfqai00jdklgu89Qi+ulcJS9OLj/lp7lNJf8A9bTKso1p1UR+rx459g50Kpq2F12JBTKE2Xl1MhbJl49AZaD/lnodCJeoD730GpK0j0bG8z4kimkPc7M+ZP+Xh1PtJN6zMcyPKdXZTzQDz7/v6/7bpjA7KvI2Y71AgdXOaM5lL0eJFKbRoliCEq4Gv0CM7YNShLw1Q5hWfrfol7J0omrM+4fgCiuZx8FuBWaZe2mMYa9wHcs6Bt+mt7A/iszsmvpJPK8ZyQVfQ4tmWZX5jQk5HsQElzqWsStcYAWwpuyMZ8caVV4KvcEHsMmwKxvXVUaQ4CSR0BOUBerULd66fI0AFKq7NwW2TzHQGcPtSY8kmTFDxTzzaHDd5NcX3TzZ84p3mfOMxeNldVlJboDsGz7WgV6ZyGaSCQ6h4aQwfdlvsDiFYIhzohMf0CbpKs+y1E+6MYvpjbAOiLFUd7FUOvdvMrGekErJGgBfbctIfdEmR/iiKJFq4yLwVxgzkrGsW9vvRH5JPy3spKSmONclE0XEErLX9wvBmETzxBkIgAmkLvQkHFiWNJSiWLH9mikeivA/8MSAqoRhXpjj33LxJkWM+sW7qSS3frMal6rf6K2UzJEXnbhZiXPgdPmJnQw6cJ2FC9XaeE1bMoUA3ItvYXbETbvjRlCPLFwSCDvLIH30U8="
